FROM gliderlabs/alpine:3.2

ENV AWS_ACCESS_KEY_ID=""
ENV AWS_SECRET_ACCESS_KEY=""
ENV AWS_DEFAULT_REGION=""

ENV HAILCANNON_ADDRESS=""
ENV HAILCANNON_SPANX_ADDRESS=""
ENV HAILCANNON_KEELHAUL_ADDRESS=""
ENV HAILCANNON_CERT="cert.pem"
ENV HAILCANNON_CERT_KEY="key.pem"
ENV APPENV ""

RUN apk add --update bash ca-certificates

COPY run.sh /
COPY target/linux/amd64/bin/* /

EXPOSE 9109
CMD ["/hailcannon"]
